language: python
python:
- 2.7
- 3.6
install:
- pip install -r requirements-dev.txt
- pip install coveralls pytest-cov pytest-pep8
script:
- py.test README.rst tests/ --cov pyriform --pep8
branches:
  except:
  - skeleton
deploy:
  provider: pypi
  server: https://upload.pypi.org/legacy/
  on:
    tags: true
    all_branches: true
  user: amc6010
  distributions: dists
  password:
    secure: nOx9qdUkT2LDUK2QQcReQ+woOl4OTnHJvp5Xw9+BCEGrdnVLC+cNCfw1eOTTbPbgFjnIyniAPs0C+/ESAQw+39BhFdbZF+ZEcvLez6Xi4B8acRMF7KYclKmwVAkSqs/gmOPk4wh7g9m3tBcID7qTbicOMA+OHbO9meroUw9azketa80PPF2/UxmElAU8HVKp5t6yx9dX+/7Xc4tI0GlJJzBsZm4SkRqkY6HhLhMseg+O+RAiK78D5inaBLQKSXB2D76GDR3Djq8HpVwzsM5A/rsKcpNb3DoCe+IkShBP0nmqUabFt+2+/6XrplIIzZR5mGDrcu/fwFBc5qAuRElrVW7QEUz3sdBwCCAf0AgsZbBqzRp26eJozU/CRa4WxAaMj0N3ELzLt3uNkD7SSMHmJ1s4xigD37C8Qvgjh/w8cvVd1odISvSu/k40niiVjGQBCqxRGtHKeUxw/6B+og3Xjb2UHMb5knXmrSCeQH7lnQYw7Bi73tceNLtcRVwdjl/LLxA2nWhkP36KYiU2/aaxjXPGnPk77PCa/W8L0luqytUdVVFBzX9TzcoPjN6jctEsWxTdbJTemQ+k+kWleeJrhm4nchjC5PVbZ0CMZLsBe4u/x/bFGV8bhKxw2A3rusLXOrfc5tO9emVBHgThWPNdlkJXOBU4W2BdHAzEDkGqGqE=
after_success:
- coveralls
