language: python
python:
- 2.7
- 3.6
before_install:
- "! grep -R SKELETON | grep -v grep"
install:
- pip install -r requirements-dev.txt
- pip install coveralls pytest-cov
script:
- python setup.py checkdocs
- py.test --cov pyriform
- sphinx-build -W docs/ build/docs/
- pylint --disable=W pyriform.py
after_script:
- flake8
- pylint pyriform.py
branches:
  except:
  - skeleton
deploy:
  provider: pypi
  server: https://upload.pypi.org/legacy/
  on:
    tags: true
    all_branches: true
  user: amc6010
  distributions: dists
  password:
    secure: BmnIBfsAQaSZ2ATRnJTFK3FuSu5YCHPVF3v/NugWy7KvbidpeIfbAix1btGntMlnbWkp47fbgXCKffAF/Dt/PCYIyCV85WmlDPPa471DLHOwRsHGf4GWgeS7IfZZNUkoP8uY4jsy0kCK4HXSzcfWJ/95mm+ESX6eyb8174ewyji2szseFWi13t/h6vlOovmCJwfZOlOlMz85JngxeANodTqKBhjzK0ljspj9+3i6O9jQdMHxubiIQdqtcJUtl7qiQZcvAHiIutuUW2A2TBDr76gF6LAbQxBnIZqv6OZZXbjDKbVySnmusjMAC/lkWFFrEr0kphkWcWMciO/+aEkHffvm91VMYGCxkpV8tSmJuCzIMUqY7VCO33zAS4rgm5qr0EJLDHiM6aaO+T55R76xkzg6YoSRNbeO49CPexSIA7RXdtgyI0c6EtZxFqvjtmmCBd4P96/cL+Bps1wdiI0obST0MBUeEFziRuE7vqGUVA8FQWuV6p5f+uw1w5N6WATV7Aw2jBMoGWf92xOu1qYwh5dlTqgM398bNyEvzUkkfHk5QbUslJf8ZV7eROu2IM3fK9PJc1/hKlVNowp0PjWhcePJUAyejGRoU54Bbs19ozIHfGgHcf7Z8A+lEyV2bkmiy3gBZG0XfdJR45R7zYpSHJiEr9Gk35zFk3CnLJO6DC4=
after_success:
- coveralls
