language: python
python:
- 2.7
- 3.6
install:
- pip install -r requirements-dev.txt
- pip install coveralls pytest-cov pytest-pep8
script:
- py.test README.rst tests/ --cov pyriform --pep8
branches:
  except:
  - skeleton
deploy:
  provider: pypi
  server: https://upload.pypi.org/legacy/
  on:
    tags: true
    all_branches: true
  user: amc6010
  distributions: dists
  password:
    secure: FwOY0xUo0VRkjjXGEo6DMJI78fG8Ha+Lsw5YkFnsI8NGbZOLIir3kurhwRXPTN0THIF/MDUEgJaZ0t5EvYY/PQkUJu+HDy/tBS6QXxDlW5tSKlkSIM1GkjessnZ+QdiHydDQzaa6LXKk81Ij4PFVZa24WK5gYNwF8+vHdb96F6uMV56IUH9qRGN1v0D1klyTzXle72p4NaNDmSK3XI+83fxlZ2xfP6Y6hTQaC/FuE/DEE9oza8PLmev2bpuq/vP4LW+PWp/+Do4Y8x4A0tHVih1ky4he2wb9Da7z2U71ZkOKyQb48GgZrg0jMuc0x96dpsI9uGw20hwWcfuLEZcxuMriY0FvTgDfHGCoNQBazJ5BDNzx6eET/4qMUJi1zeLsmUP1VhCX4+uwI1jPXmvOh2ZV8eJdXNjpEyhFhGNIgf2vOQxiLhbcw5pERcuA81G9NIstizKguLDK2Of+VphFnbBVfN+CoR2zgQNSkqEOTr82FFz+yY6sLwMBvSsnXcKAOo5uQXZDTjReUZoeML+XfbzioPyzdRuOM9PdW88YyD8bBHwth6rQwra1VHhJYnraqJjzCPz9rOyxr0qP8if/8r7jI+YH6UTf526Os3XUJXhQUhL/3kufkPUlBk2uc10zONs1PRuCj3nz/3gCHf1ywV0kyfNOBBqDQYqG0BKIjiA=
after_success:
- coveralls
